version: '3.8'

services:
  api:
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
